version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpadsds12ssword
      MYSQL_DATABASE: photoservice_db
    ports:
      - "3306:3306"
    networks:
      - photoservice_network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

  minio:
    image: minio/minio:latest
    container_name: minio-report-management
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"
    networks:
      - photoservice_network

networks:
  photoservice_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  miniodata:
    driver: local